[package]
name = "stuff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
raylib = "3.7.0"
time = { version = "0.3.36" }
time-macros = { version = "0.2.0-alpha.1" }
